version: "3.7"

services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prisma
    volumes:
      - ./data/db:/var/lib/postgresql/data
